# Generated by Django 4.1.2 on 2022-10-23 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_names', models.TextField()),
                ('useful_idea', models.TextField()),
                ('changes_suggested', models.TextField()),
                ('topics_for_future', models.TextField()),
                ('additional_comments', models.TextField()),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workshop', models.TextField(unique=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.feedback')),
            ],
        ),
    ]
