# Generated by Django 4.1.2 on 2022-10-23 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='guest',
        ),
        migrations.AddField(
            model_name='workshop',
            name='feedback',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.feedback'),
            preserve_default=False,
        ),
    ]
