# Generated by Django 4.1.2 on 2022-10-23 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_workshop_guest_workshop_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='Workshop',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.workshop'),
            preserve_default=False,
        ),
    ]
