# Generated by Django 4.1.2 on 2022-10-23 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_workshop_feedback_feedback_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty', models.TextField(unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Workshop',
            new_name='workshop',
        ),
        migrations.AddField(
            model_name='feedback',
            name='faculty',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.faculty'),
            preserve_default=False,
        ),
    ]
