import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { Footer } from '../components/footer'
import { Logo } from '../components/logo'
import { ProgressBar } from '../components/progressbar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [percentage, setPercentage] = useState(10);
  return (
    <div>
      <Head>
        <title>Brightspace Participation form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ProgressBar percentage={percentage} />
        <Logo />
        <h1 className={styles.title}>
          <a href="https://brightspace.uwindsor.ca/">Brightspace</a> Survey </h1>

        <p className={styles.description}>
          <code>Welcome!!!</code> How can we help you today?
        </p>

        <div className={styles.grid}>
          <a href=" https://ctl2.uwindsor.ca/workshops/145/" className={styles.card}>
            <h2>Workshops &rarr;</h2>
            <p> Further develop teaching and learning and utilizing Brightspace.</p>
          </a>
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Survey &rarr;</h2>
            <p>  Providing valuable feedback about the session you attended.</p>
          </a>
          <a href="https://blackboard.ca/bbcafe" className={styles.card}>
            <h2> BBCafe &rarr;</h2>
            <p> Take assistance from our trained assistants to naviagate issues.</p>
          </a>
          <a href="https://uwindsor.teamdynamix.com/" className={styles.card}>
            <h2>TDX &rarr;</h2>
            <p>  Raise tickets for teachnical issues realted to Brightspace.</p>
          </a>
       
        </div>
      </main>

      <Footer />
    </div>
  )
}

export default Home
